services:
  karaoke-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: karaoke
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d  # Directory for init scripts
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d karaoke" ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  karaoke-service:
    build: .
    depends_on:
      karaoke-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://karaoke-db:5432/karaoke?currentSchema=karaoke_schema
      SPRING_DATASOURCE_USERNAME: karaoke_user
      SPRING_DATASOURCE_PASSWORD: karaoke_pass
    volumes:
      - ./input:/input
      - ./output:/output

volumes:
  db_data: